Vagrant.configure("2") do |config|

    #Configurando a VM
    config.vm.define:teste do |teste_config|
        teste_config.vm.box = "centos/7"
        teste_config.vm.network "private_network", ip: "192.168.50.10"
        teste_config.vm.provider:virtualbox do |v|
            v.memory = 1024
            v.cpus = 1
        end
    end

end

